apiVersion: apps/v1
kind: Deployment
metadata:
  name: inlaze-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inlaze
  template:
    metadata:
      labels:
        app: inlaze
    spec:
      containers:
      - name: inlaze-container
        image: zafo351/inlaze-test-devops
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: inlaze-service
  namespace: default
spec:
  selector:
    app: inlaze
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
